#ifndef TCP_INSPECTION_ERRORS
#define TCP_INSPECTION_ERRORS

#define TCP_INSPECTION_NO_ERROR 							0
#define TCP_INSPECTION_NULL_POINTER							1
#define TCP_INSPECTION_CANNOT_GET_SYSCALL_TABLE_ADDR		2
#define TCP_INSPECTION_CANNOT_CHANGE_PAGE_PROTECTION		3
#define TCP_INSPECTION_FD_IS_NOT_SOCKET						4
#define TCP_INSPECTION_NOT_FOUND							5
#define TCP_INSPECTION_INVALID_SOCKET						6

#endif
